# Generated by Django 6.0.5 on 2026-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature Related'), ('health', 'Health Related'), ('tech', 'Tech Related')], default='tech', max_length=50),
        ),
    ]
